# version: 1.0.0 - HACKER STYLE

add_newline = false
continuation_prompt = "[➤➤](dimmed white)"

format = """$directory$fill$git_branch$git_status$cmd_duration\n$username$hostname$sudo$character"""

right_format = """
$shlvl\
$jobs\
$time\
$python\
$nodejs\
$rust\
$package\
$memory_usage\
$status
"""

[fill]
symbol = " "

[character]
success_symbol = "[➤](bold bright-green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[↪](bold yellow)"
format = "$symbol "

[username]
format = "[☠ $user]($style) "
style_user = "bold bright-yellow"
style_root = "bold bright-red"
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname]($style) "
style = "dimmed white"

[sudo]
format = "[⚡]($style)"
style = "bold bright-red"
disabled = false

[directory]
style = "bold cyan"
format = "[▚ $path]($style) "
read_only = " [LOCKED]"
truncation_length = 3
truncation_symbol = "…"

[cmd_duration]
format = "[⏱ $duration](dimmed white) "
min_time = 500

[jobs]
symbol = "⚙ "
style = "bold white"
format = "[$symbol$number]($style) "

[time]
disabled = false
format = "[⧖ $time]($style)"
time_format = "%H:%M"
style = "italic dimmed white"

[memory_usage]
format = "[MEM: $ram]($style) "
threshold = 70
style = "bold bright-purple"
disabled = false

[status]
format = "[$symbol$status]($style)"
symbol = "✗"
style = "bold red"
disabled = false

# ── Git ───────────────────────────────
[git_branch]
symbol = "⭠ "
format = "[$symbol$branch]($style) "
style = "bold green"

[git_status]
style = "dimmed white"
format = "([$all_status$ahead_behind]($style))"
conflicted = "⚔"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = "💾"
modified = "*"
staged = "+"
renamed = "»"
deleted = "✘"

# ── Languages ─────────────────────────

[python]
format = "[PY ⌉ $version]($style) "
style = "bold bright-yellow"
symbol = "🐍"
version_format = "${raw}"

[nodejs]
format = "[NODE ◫ $version]($style) "
style = "bold green"
version_format = "${raw}"

[rust]
format = "[RS ⊃ $version]($style) "
style = "bold red"
version_format = "${raw}"

[package]
format = "[📦 $version]($style)"
style = "dimmed white"
version_format = "${raw}"
